from .student import (
    AcademicTerm,
    Attendance,
    Class,
    ClassSchedule,
    ClassSubject,
    Enrollment,
    Permission,
    RolePermission,
    Room,
    Score,
    Student,
    Subject,
    SubjectTeacher,
    Teacher,
    User,
)

__all__ = [
    "AcademicTerm",
    "Attendance",
    "Class",
    "ClassSchedule",
    "ClassSubject",
    "Enrollment",
    "Permission",
    "RolePermission",
    "Room",
    "Score",
    "Student",
    "Subject",
    "SubjectTeacher",
    "Teacher",
    "User",
]
