import React, { createContext, useEffect, useMemo, useState } from 'react';

export const LanguageContext = createContext();

const translations = {
  vi: {
    common: {
      dashboard: 'Tổng quan',
      students: 'Sinh viên',
      classes: 'Lớp học',
      subjects: 'Môn học',
      scores: 'Điểm số',
      logout: 'Đăng xuất',
      studentManagementSystem: 'Student Management System',
      loading: 'Đang tải...',
      noData: 'Không có dữ liệu',
      exportCsv: 'Xuất CSV',
      addNew: 'Thêm mới',
      save: 'Lưu',
      update: 'Cập nhật',
      cancel: 'Hủy',
      search: 'Tìm kiếm',
      actions: 'Thao tác',
      status: 'Trạng thái',
      edit: 'Sửa',
      delete: 'Xóa',
      close: 'Đóng',
      roleRestricted: 'Bạn không có quyền thực hiện thao tác này.'
    },
    login: {
      portal: 'SMS Portal',
      title: 'Student Management System',
      showcaseKicker: 'Student Management System',
      showcaseTitle: 'HỆ THỐNG\nQUẢN LÝ SINH VIÊN',
      description:
        'Hệ thống nội bộ hỗ trợ quản lý sinh viên, lớp học và quy trình học tập trên một giao diện tập trung.',
      access: 'Truy cập mọi lúc',
      flow: 'Đăng nhập nhanh gọn',
      secure: 'Phân quyền an toàn',
      welcome: 'Chào mừng trở lại',
      signIn: 'Đăng nhập',
      username: 'Tên đăng nhập',
      usernamePlaceholder: 'Nhập tên đăng nhập',
      password: 'Mật khẩu',
      passwordPlaceholder: 'Nhập mật khẩu',
      loginButton: 'Đăng nhập',
      loggingIn: 'Đang đăng nhập...',
      accountNotice: 'Tài khoản được cấp bởi nhà trường hoặc quản trị viên.',
      supportNotice: 'Nếu bạn chưa có tài khoản, vui lòng liên hệ phòng đào tạo hoặc admin hệ thống.'
    },
    navbar: {
      userRole: {
        student: 'Sinh viên',
        teacher: 'Giảng viên',
        admin: 'Quản trị viên'
      }
    },
    dashboard: {
      title: 'Tổng quan',
      welcome: 'Dữ liệu tổng hợp từ hệ thống quản lý sinh viên',
      totalStudents: 'Tổng sinh viên',
      totalClasses: 'Tổng lớp học',
      totalSubjects: 'Tổng môn học',
      averageScore: 'Điểm trung bình',
      recentActivity: 'Cập nhật gần đây',
      noRecentActivity: 'Chưa có hoạt động gần đây',
      quickActions: 'Tác vụ nhanh',
      addStudent: 'Thêm sinh viên',
      addClass: 'Thêm lớp học',
      addSubject: 'Thêm môn học',
      recordScore: 'Nhập điểm',
      latestStudents: 'Sinh viên mới cập nhật',
      dataSummary: 'Tóm tắt dữ liệu'
    },
    studentsPage: {
      title: 'Quản lý sinh viên',
      addStudent: 'Thêm sinh viên',
      editStudent: 'Cập nhật sinh viên',
      searchPlaceholder: 'Tìm sinh viên theo tên hoặc email...',
      loadingStudents: 'Đang tải danh sách sinh viên...',
      noStudentsFound: 'Không tìm thấy sinh viên',
      confirmDelete: 'Bạn có chắc muốn xóa sinh viên này không?',
      studentId: 'Mã sinh viên',
      name: 'Họ tên',
      email: 'Email',
      phone: 'Số điện thoại',
      class: 'Lớp',
      status: 'Trạng thái',
      actions: 'Thao tác',
      view: 'Xem',
      edit: 'Sửa',
      delete: 'Xóa',
      active: 'Đang học',
      inactive: 'Tạm dừng',
      graduated: 'Đã tốt nghiệp',
      suspended: 'Đình chỉ',
      importExcel: 'Nhập từ Excel',
      importDescription:
        'Dán dữ liệu đã copy từ Excel hoặc tải file CSV/TSV để thêm nhiều sinh viên cùng lúc.',
      importPlaceholder:
        'mã_sinh_viên\ttên\thọ\temail\tsố_điện_thoại\tngày_sinh\tgiới_tính\tđịa_chỉ\tmã_lớp\tngày_nhập_học\ttrạng_thái'
    },
    studentForm: {
      studentId: 'Mã sinh viên',
      firstName: 'Tên',
      lastName: 'Họ',
      email: 'Email',
      phone: 'Số điện thoại',
      dateOfBirth: 'Ngày sinh',
      gender: 'Giới tính',
      address: 'Địa chỉ',
      class: 'Lớp',
      enrollmentDate: 'Ngày nhập học',
      status: 'Trạng thái',
      saveStudent: 'Lưu sinh viên',
      updateStudent: 'Cập nhật sinh viên',
      saving: 'Đang lưu...',
      placeholderStudentId: 'Ví dụ: SV001',
      placeholderClassId: 'Mã lớp',
      requiredStudentId: 'Mã sinh viên là bắt buộc',
      requiredFirstName: 'Tên là bắt buộc',
      requiredLastName: 'Họ là bắt buộc',
      requiredEmail: 'Email là bắt buộc',
      requiredClass: 'Lớp là bắt buộc',
      male: 'Nam',
      female: 'Nữ',
      other: 'Khác',
      active: 'Đang học',
      inactive: 'Tạm dừng',
      graduated: 'Đã tốt nghiệp',
      suspended: 'Đình chỉ'
    },
    classesPage: {
      title: 'Quản lý lớp học',
      addClass: 'Thêm lớp học',
      editClass: 'Cập nhật lớp học',
      searchPlaceholder: 'Tìm lớp theo tên hoặc niên khóa...',
      noClassesFound: 'Không tìm thấy lớp học',
      loadingClasses: 'Đang tải danh sách lớp học...',
      confirmDelete: 'Bạn có chắc muốn xóa lớp học này không?',
      name: 'Tên lớp',
      gradeLevel: 'Khối',
      academicYear: 'Niên khóa',
      capacity: 'Sức chứa',
      description: 'Mô tả',
      homeroomTeacher: 'Giáo viên chủ nhiệm'
    },
    subjectsPage: {
      title: 'Quản lý môn học',
      addSubject: 'Thêm môn học',
      editSubject: 'Cập nhật môn học',
      searchPlaceholder: 'Tìm môn học theo tên hoặc mã môn...',
      noSubjectsFound: 'Không tìm thấy môn học',
      loadingSubjects: 'Đang tải danh sách môn học...',
      confirmDelete: 'Bạn có chắc muốn xóa môn học này không?',
      name: 'Tên môn',
      code: 'Mã môn',
      credits: 'Số tín chỉ',
      description: 'Mô tả',
      active: 'Đang mở',
      inactive: 'Tạm khóa'
    },
    scoresPage: {
      title: 'Quản lý điểm số',
      addScore: 'Thêm điểm',
      editScore: 'Cập nhật điểm',
      loadingScores: 'Đang tải danh sách điểm...',
      noScoresFound: 'Không có dữ liệu điểm',
      confirmDelete: 'Bạn có chắc muốn xóa điểm này không?',
      enrollmentId: 'Mã đăng ký học',
      scoreType: 'Loại điểm',
      score: 'Điểm',
      maxScore: 'Điểm tối đa',
      weight: 'Trọng số',
      grade: 'Xếp loại',
      examDate: 'Ngày kiểm tra',
      remarks: 'Ghi chú',
      searchPlaceholder: 'Tìm theo mã đăng ký học hoặc loại điểm...',
      quiz: 'Bài kiểm tra',
      assignment: 'Bài tập',
      midterm: 'Giữa kỳ',
      final: 'Cuối kỳ',
      practice: 'Thực hành'
    }
  },
  en: {
    common: {
      dashboard: 'Dashboard',
      students: 'Students',
      classes: 'Classes',
      subjects: 'Subjects',
      scores: 'Scores',
      logout: 'Logout',
      studentManagementSystem: 'Student Management System',
      loading: 'Loading...',
      noData: 'No data',
      exportCsv: 'Export CSV',
      addNew: 'Add new',
      save: 'Save',
      update: 'Update',
      cancel: 'Cancel',
      search: 'Search',
      actions: 'Actions',
      status: 'Status',
      edit: 'Edit',
      delete: 'Delete',
      close: 'Close',
      roleRestricted: 'You do not have permission to perform this action.'
    },
    login: {
      portal: 'SMS Portal',
      title: 'Student Management System',
      showcaseKicker: 'Student Management System',
      showcaseTitle: 'STUDENT\nMANAGEMENT\nSYSTEM',
      description:
        'An internal portal for managing students, classes, and academic workflows in one place.',
      access: 'Access anywhere',
      flow: 'Simple login flow',
      secure: 'Role-based access',
      welcome: 'Welcome back',
      signIn: 'Sign in',
      username: 'Username',
      usernamePlaceholder: 'Enter your username',
      password: 'Password',
      passwordPlaceholder: 'Enter your password',
      loginButton: 'Login',
      loggingIn: 'Logging in...',
      accountNotice: 'Accounts are issued by the school or system administrator.',
      supportNotice: 'If you do not have an account yet, please contact your administrator.'
    },
    navbar: {
      userRole: {
        student: 'Student',
        teacher: 'Teacher',
        admin: 'Admin'
      }
    },
    dashboard: {
      title: 'Dashboard',
      welcome: 'Live summary from the student management system',
      totalStudents: 'Total students',
      totalClasses: 'Total classes',
      totalSubjects: 'Total subjects',
      averageScore: 'Average score',
      recentActivity: 'Recent activity',
      noRecentActivity: 'No recent activity to display',
      quickActions: 'Quick actions',
      addStudent: 'Add student',
      addClass: 'Add class',
      addSubject: 'Add subject',
      recordScore: 'Record score',
      latestStudents: 'Recently updated students',
      dataSummary: 'Data summary'
    },
    studentsPage: {
      title: 'Student Management',
      addStudent: 'Add student',
      editStudent: 'Edit student',
      searchPlaceholder: 'Search students by name or email...',
      loadingStudents: 'Loading students...',
      noStudentsFound: 'No students found',
      confirmDelete: 'Are you sure you want to delete this student?',
      studentId: 'Student code',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      class: 'Class',
      status: 'Status',
      actions: 'Actions',
      view: 'View',
      edit: 'Edit',
      delete: 'Delete',
      active: 'Active',
      inactive: 'Inactive',
      graduated: 'Graduated',
      suspended: 'Suspended',
      importExcel: 'Import from Excel',
      importDescription:
        'Paste data copied from Excel or upload a CSV/TSV file to add multiple students at once.',
      importPlaceholder:
        'student_code\tfirst_name\tlast_name\temail\tphone\tdate_of_birth\tgender\taddress\tclass_id\tenrollment_date\tstatus'
    },
    studentForm: {
      studentId: 'Student code',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email',
      phone: 'Phone',
      dateOfBirth: 'Date of birth',
      gender: 'Gender',
      address: 'Address',
      class: 'Class',
      enrollmentDate: 'Enrollment date',
      status: 'Status',
      saveStudent: 'Save student',
      updateStudent: 'Update student',
      saving: 'Saving...',
      placeholderStudentId: 'e.g. SV001',
      placeholderClassId: 'Class ID',
      requiredStudentId: 'Student code is required',
      requiredFirstName: 'First name is required',
      requiredLastName: 'Last name is required',
      requiredEmail: 'Email is required',
      requiredClass: 'Class is required',
      male: 'Male',
      female: 'Female',
      other: 'Other',
      active: 'Active',
      inactive: 'Inactive',
      graduated: 'Graduated',
      suspended: 'Suspended'
    },
    classesPage: {
      title: 'Class Management',
      addClass: 'Add class',
      editClass: 'Edit class',
      searchPlaceholder: 'Search classes by name or academic year...',
      noClassesFound: 'No classes found',
      loadingClasses: 'Loading classes...',
      confirmDelete: 'Are you sure you want to delete this class?',
      name: 'Class name',
      gradeLevel: 'Grade level',
      academicYear: 'Academic year',
      capacity: 'Capacity',
      description: 'Description',
      homeroomTeacher: 'Homeroom teacher'
    },
    subjectsPage: {
      title: 'Subject Management',
      addSubject: 'Add subject',
      editSubject: 'Edit subject',
      searchPlaceholder: 'Search subjects by name or code...',
      noSubjectsFound: 'No subjects found',
      loadingSubjects: 'Loading subjects...',
      confirmDelete: 'Are you sure you want to delete this subject?',
      name: 'Subject name',
      code: 'Code',
      credits: 'Credits',
      description: 'Description',
      active: 'Active',
      inactive: 'Inactive'
    },
    scoresPage: {
      title: 'Score Management',
      addScore: 'Add score',
      editScore: 'Edit score',
      loadingScores: 'Loading scores...',
      noScoresFound: 'No scores found',
      confirmDelete: 'Are you sure you want to delete this score?',
      enrollmentId: 'Enrollment ID',
      scoreType: 'Score type',
      score: 'Score',
      maxScore: 'Max score',
      weight: 'Weight',
      grade: 'Grade',
      examDate: 'Exam date',
      remarks: 'Remarks',
      searchPlaceholder: 'Search by enrollment ID or score type...',
      quiz: 'Quiz',
      assignment: 'Assignment',
      midterm: 'Midterm',
      final: 'Final',
      practice: 'Practice'
    }
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('app_language') || 'vi');

  useEffect(() => {
    localStorage.setItem('app_language', language);
    document.documentElement.lang = language === 'vi' ? 'vi' : 'en';
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: translations[language]
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};
